apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snow-ai-dev
resources:
  - ../../base
replicas:
  - name: agent-orchestrator
    count: 1
  - name: control-tower
    count: 1
  - name: mcp-a2a-gateway
    count: 1
  - name: llm-gateway
    count: 1
